### ISSUE TITLE
Рекомендация по улучшению @mixin-lg итд

### ISSUE THREAD

**Issue by enkos** [dmitry-lavrik/smart-grid#3]
## Сейчас имеем
```scss
@mixin lg($name, $value){
    @media screen and (max-width: $break_lg) {
        #{$name}: $value;
    }
}
```

И если нужно переопределить несколько стилей для другого разрешения экрана
```scss
.btn {
    @include lg (position, absolute)
    @include lg (display, block)
    @include lg (width, 100%)
    @include lg (background-color, $main-color)
}
```

## А можно сделать так?
```scss
@mixin lg {
  @media only screen and (max-width: $break_lg) {
    @content;
  }
}
```

и тогда проще переопределять стили
```scss
.btn {
    @include lg {
        position: absolute;
        display: block;
        width: 100%;
        background-color: $main-color;
    }
}
```
