### ISSUE TITLE
col-padding() + size() не верные размеры

### ISSUE THREAD

**Issue by g-rodigy** [dmitry-lavrik/smart-grid#55]
Пример на stylus
````styl
.list
    row-flex()
    .item
        col-padding()
        size(6)
        border 1px solid #aaa
````

при таком сценарии получим (offset = 30px):
````css
.list {
    display: flex;
    flex-wrap: wrap;
    margin-left: -15px;
    margin-right: -15px;
}
.list .item {
    width: calc(50% - 30px);
    word-wrap: break-word;
    padding-left: 15px;
    padding-right: 15px;
    border: 1px solid #aaa;
}
````
Не верная  комбинация `col-padding` и `size`, в `.item` calc не нужно отнимать 30px. Да и `.row` -15px тоже нужно, ну это не критично, можно не пользоваться этим миксином тут
